# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: sudo chmod +x MCsquare/bin/MCsquare_linux
      - matlab/installss
          release: R2020a
      - run:
          name: Verify the matlab and mex scripts are available
          command: |
            set -e
            matlab -batch "assert(strcmp(version('-release'),'2020a'))"
      - matlab/run-command:
          command:  "cd unitTest; matRad_runTests;" 
orbs:
  matlab: mathworks/matlab@0.2
  shellcheck: circleci/shellcheck@2.0.0
